language: node_js
node_js: 7
script: echo “Deploy!!”
install: npm install -g firebase-tools
after_success: firebase deploy --project haifahrul-mws --token "1/koRf3xofpQZV86B7RgudCGgamqgog9fNC6hDZkJmrYw"
